name: 🐛 Bug Report
description: Report a bug or issue with FuelSOS
title: '[BUG]: '
labels: ['bug', 'hacktoberfest']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! 🎃

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Tell us what happened
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the app is affected?
      options:
        - Frontend (Flutter Mobile App)
        - Backend (Node.js API)
        - Web Demo
        - Documentation
        - Build/Configuration
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where does this bug occur?
      multiple: true
      options:
        - Android
        - Web (Chrome)
        - Windows Desktop
        - iOS
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide version information
      placeholder: |
        - Flutter version: 
        - Device: 
        - OS version:
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or logs
    validations:
      required: false
