name: ✨ Feature Request
description: Suggest a new feature for FuelSOS
title: '[FEATURE]: '
labels: ['enhancement', 'hacktoberfest']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the app would this affect?
      options:
        - Frontend (Flutter Mobile App)
        - Backend (Node.js API)
        - Web Demo
        - Documentation
        - Build/Configuration
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for functionality
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add mockups, examples, or any other context
    validations:
      required: false
